export const agentData = [
  {
    id: 4,
    name: "John Doe",
    profileImage: "https://via.placeholder.com/120",
    agency: "Emtan Construction",
    rating: 4.5,
    votes: 133,
    experience: "3 years",
    sales: 150,
    activePosts: 25,
  },
  {
    id: 5,
    name: "Jane Doe",
    profileImage: "https://via.placeholder.com/120",
    agency: "Emtan Construction",
    rating: 4.7,
    votes: 200,
    experience: "5 years",
    sales: 180,
    activePosts: 30,
  },
  {
    id: 6,
    name: "Alice Smith",
    profileImage: "https://via.placeholder.com/120",
    agency: "Emtan Construction",
    rating: 4.6,
    votes: 150,
    experience: "4 years",
    sales: 160,
    activePosts: 28,
  },
  {
    id: 7,
    name: "Bob Johnson",
    profileImage: "https://via.placeholder.com/120",
    agency: "Emtan Construction",
    rating: 4.8,
    votes: 220,
    experience: "6 years",
    sales: 190,
    activePosts: 35,
  },
  {
    id: 8,
    name: "Charlie Brown",
    profileImage: "https://via.placeholder.com/120",
    agency: "Emtan Construction",
    rating: 4.4,
    votes: 110,
    experience: "2 years",
    sales: 140,
    activePosts: 20,
  },
  {
    id: 9,
    name: "David Wilson",
    profileImage: "https://via.placeholder.com/120",
    agency: "Emtan Construction",
    rating: 4.9,
    votes: 250,
    experience: "7 years",
    sales: 200,
    activePosts: 40,
  },
  {
    id: 10,
    name: "Eve Davis",
    profileImage: "https://via.placeholder.com/120",
    agency: "Emtan Construction",
    rating: 4.3,
    votes: 100,
    experience: "1 year",
    sales: 130,
    activePosts: 18,
  },
  {
    id: 11,
    name: "Frank Miller",
    profileImage: "https://via.placeholder.com/120",
    agency: "Emtan Construction",
    rating: 4.7,
    votes: 210,
    experience: "5 years",
    sales: 170,
    activePosts: 32,
  },
];

// Compare this snippet from flatty_frontend/src/pages/Agents.jsx:
