export const apartmentData = [
  {
    id: 1,
    agentId: 1,
    title: "Luxury Apartment in City Center",
    price: 250000,
    location: "Downtown, New York",
    bedrooms: 3,
    bathrooms: 2,
    area: "1200 sqft",
    image: "https://via.placeholder.com/1920x1080",
    status: "For Sale",
  },
  {
    id: 2,
    agentId: 1,
    title: "Modern Apartment with Sea View",
    price: 300000,
    location: "Miami Beach, Florida",
    bedrooms: 2,
    bathrooms: 2,
    area: "1100 sqft",
    image: "https://via.placeholder.com/1920x1080",
    status: "For Sale",
  },
  // Add more apartment objects here
  {
    id: 3,
    agentId: 1,
    title: "Cozy Apartment in Suburbs",
    price: 150000,
    location: "Suburbs, Chicago",
    bedrooms: 2,
    bathrooms: 1,
    area: "900 sqft",
    image: "https://via.placeholder.com/1920x1080",
    status: "For Sale",
  },
  {
    id: 4,
    agentId: 1,
    title: "Spacious Apartment with Garden",
    price: 350000,
    location: "San Francisco, California",
    bedrooms: 4,
    bathrooms: 3,
    area: "1500 sqft",
    image: "https://via.placeholder.com/1920x1080",
    status: "For Sale",
  },
  {
    id: 5,
    agentId: 1,
    title: "Penthouse with City View",
    price: 500000,
    location: "Manhattan, New York",
    bedrooms: 3,
    bathrooms: 2,
    area: "1300 sqft",
    image: "https://via.placeholder.com/1920x1080",
    status: "For Sale",
  },
  {
    id: 6,
    agentId: 1,
    title: "Affordable Apartment",
    price: 100000,
    location: "Brooklyn, New York",
    bedrooms: 1,
    bathrooms: 1,
    area: "700 sqft",
    image: "https://via.placeholder.com/1920x1080",
    status: "For Sale",
  },
  {
    id: 7,
    agentId: 1,
    title: "Luxury Apartment in City Center",
    price: 250000,
    location: "Downtown, New York",
    bedrooms: 3,
    bathrooms: 2,
    area: "1200 sqft",
    image: "https://via.placeholder.com/1920x1080",
    status: "For Sale",
  },
  {
    id: 8,
    agentId: 1,
    title: "Modern Apartment with Sea View",
    price: 300000,
    location: "Miami Beach, Florida",
    bedrooms: 2,
    bathrooms: 2,
    area: "1100 sqft",
    image: "https://via.placeholder.com/1920x1080",
    status: "For Sale",
  },
  {
    id: 9,
    agentId: 1,
    title: "Cozy Apartment in Suburbs",
    price: 150000,
    location: "Suburbs, Chicago",
    bedrooms: 2,
    bathrooms: 1,
    area: "900 sqft",
    image: "https://via.placeholder.com/1920x1080",
    status: "For Sale",
  },
  {
    id: 10,
    agentId: 1,
    title: "Spacious Apartment with Garden",
    price: 350000,
    location: "San Francisco, California",
    bedrooms: 4,
    bathrooms: 3,
    area: "1500 sqft",
    image: "https://via.placeholder.com/1920x1080",
    status: "For Sale",
  },
  {
    id: 11,
    agentId: 1,
    title: "Penthouse with City View",
    price: 500000,
    location: "Manhattan, New York",
    bedrooms: 3,
    bathrooms: 2,
    area: "1300 sqft",
    image: "https://via.placeholder.com/1920x1080",
    status: "For Sale",
  },
  {
    id: 12,
    agentId: 1,
    title: "Affordable Apartment",
    price: 100000,
    location: "Brooklyn, New York",
    bedrooms: 1,
    bathrooms: 1,
    area: "700 sqft",
    image: "https://via.placeholder.com/1920x1080",
    status: "For Sale",
  },
  {
    id: 13,
    agentId: 1,
    title: "Luxury Apartment in City Center",
    price: 250000,
    location: "Downtown, New York",
    bedrooms: 3,
    bathrooms: 2,
    area: "1200 sqft",
    image: "https://via.placeholder.com/1920x1080",
    status: "For Sale",
  },
  {
    id: 14,
    agentId: 1,
    title: "Modern Apartment with Sea View",
    price: 300000,
    location: "Miami Beach, Florida",
    bedrooms: 2,
    bathrooms: 2,
    area: "1100 sqft",
    image: "https://via.placeholder.com/1920x1080",
    status: "For Sale",
  },
  {
    id: 15,
    agentId: 1,
    title: "Cozy Apartment in Suburbs",
    price: 150000,
    location: "Suburbs, Chicago",
    bedrooms: 2,
    bathrooms: 1,
    area: "900 sqft",
    image: "https://via.placeholder.com/1920x1080",
    status: "For Sale",
  },
  {
    id: 16,
    agentId: 1,
    title: "Spacious Apartment with Garden",
    price: 350000,
    location: "San Francisco, California",
    bedrooms: 4,
    bathrooms: 3,
    area: "1500 sqft",
    image: "https://via.placeholder.com/1920x1080",
    status: "For Sale",
  },
  {
    id: 17,
    agentId: 1,
    title: "Penthouse with City View",
    price: 500000,
    location: "Manhattan, New York",
    bedrooms: 3,
    bathrooms: 2,
    area: "1300 sqft",
    image: "https://via.placeholder.com/1920x1080",
    status: "For Sale",
  },
  {
    id: 18,
    agentId: 1,
    title: "Affordable Apartment",
    price: 100000,
    location: "Brooklyn, New York",
    bedrooms: 1,
    bathrooms: 1,
    area: "700 sqft",
    image: "https://via.placeholder.com/1920x1080",
    status: "For Sale",
  },
  {
    id: 19,
    agentId: 1,
    title: "Luxury Apartment in City Center",
    price: 250000,
    location: "Downtown, New York",
    bedrooms: 3,
    bathrooms: 2,
    area: "1200 sqft",
    image: "https://via.placeholder.com/1920x1080",
    status: "For Sale",
  },
  {
    id: 20,
    agentId: 1,
    title: "Modern Apartment with Sea View",
    price: 300000,
    location: "Miami Beach, Florida",
    bedrooms: 2,
    bathrooms: 2,
    area: "1100 sqft",
    image: "https://via.placeholder.com/1920x1080",
    status: "For Sale",
  },
];
