// Sample data for items
import apparment1 from "./assets/images/apparment1.png";
import apartment2 from "./assets/images/apparment2.png";
import apartment3 from "./assets/images/apparment3.png";
import apartment4 from "./assets/images/apparment4.png";
export const data = [
  {
    img: apparment1,
    price: "250 000",
    room: 3,
    area: 150,
    currFloor: "10",
    building: "15",
    location: "New York City, NY",
    type: "Apartment",
  },
  {
    img: apartment2,
    price: "300 000",
    room: 4,
    area: 180,
    currFloor: "10",
    building: "15",
    location: "Los Angeles, CA",
    type: "House",
  },
  {
    img: apartment3,
    price: "400 000",
    room: 5,
    area: 200,
    currFloor: "10",
    building: "15",
    location: "Miami, FL",
    type: "Villa",
  },
  {
    img: apartment4,
    price: "500 000",
    room: 6,
    area: 250,
    currFloor: "10",
    building: "15",
    location: "San Francisco, CA",
    type: "Commercial",
  },
  {
    img: apparment1,
    price: "250 000",
    room: 3,
    area: 150,
    currFloor: "10",
    building: "15",
    location: "New York City, NY",
    type: "Apartment",
  },
  {
    img: apartment2,
    price: "300 000",
    room: 4,
    area: 180,
    currFloor: "10",
    building: "15",
    location: "Los Angeles, CA",
    type: "House",
  },
  {
    img: apartment3,
    price: "400 000",
    room: 5,
    area: 200,
    currFloor: "10",
    building: "15",
    location: "Miami, FL",
    type: "Villa",
  },
  {
    img: apartment4,
    price: "500 000",
    room: 6,
    area: 250,
    currFloor: "10",
    building: "15",
    location: "San Francisco, CA",
    type: "Commercial",
  },
  {
    img: apparment1,
    price: "250 000",
    room: 3,
    area: 150,
    currFloor: "10",
    building: "15",
    location: "New York City, NY",
    type: "Apartment",
  },
  {
    img: apartment2,
    price: "300 000",
    room: 4,
    area: 180,
    currFloor: "10",
    building: "15",
    location: "Los Angeles, CA",
    type: "House",
  },
  {
    img: apartment3,
    price: "400 000",
    room: 5,
    area: 200,
    currFloor: "10",
    building: "15",
    location: "Miami, FL",
    type: "Villa",
  },
  {
    img: apartment4,
    price: "500 000",
    room: 6,
    area: 250,
    currFloor: "10",
    building: "15",
    location: "San Francisco, CA",
    type: "Commercial",
  },
];
