// Sample data for items
import apartment1 from "./assets/images/apparment1.png";
import apartment2 from "./assets/images/apparment2.png";
import apartment3 from "./assets/images/apparment3.png";
import apartment4 from "./assets/images/apparment4.png";

export const data = [
  {
    id: 1,
    images: [apartment1, apartment2, apartment3, apartment1, apartment4],
    price: "250 000",
    room: 3,
    area: 150,
    currFloor: "10",
    building: "15",
    location: "New York City, NY",
    type: "Apartment",
  },
  {
    id: 2,
    images: [apartment1, apartment2, apartment3, apartment1],
    price: "300 000",
    room: 4,
    area: 180,
    currFloor: "10",
    building: "15",
    location: "Los Angeles, CA",
    type: "House",
  },
  {
    id: 3,
    images: [apartment1, apartment2, apartment3, apartment1],
    price: "400 000",
    room: 5,
    area: 200,
    currFloor: "10",
    building: "15",
    location: "Miami, FL",
    type: "Villa",
  },
  {
    id: 4,
    images: [apartment1, apartment2, apartment3, apartment1],
    price: "500 000",
    room: 6,
    area: 250,
    currFloor: "10",
    building: "15",
    location: "San Francisco, CA",
    type: "Commercial",
  },
  {
    id: 5,
    images: [apartment1, apartment2, apartment3, apartment1],
    price: "250 000",
    room: 3,
    area: 150,
    currFloor: "10",
    building: "15",
    location: "New York City, NY",
    type: "Apartment",
  },
  {
    id: 6,
    images: [apartment1, apartment2, apartment3, apartment1],
    price: "300 000",
    room: 4,
    area: 180,
    currFloor: "10",
    building: "15",
    location: "Los Angeles, CA",
    type: "House",
  },
  {
    id: 7,
    images: [apartment1, apartment2, apartment3, apartment1],
    price: "400 000",
    room: 5,
    area: 200,
    currFloor: "10",
    building: "15",
    location: "Miami, FL",
    type: "Villa",
  },
  {
    id: 8,
    images: [apartment1, apartment2, apartment3, apartment1],
    price: "500 000",
    room: 6,
    area: 250,
    currFloor: "10",
    building: "15",
    location: "San Francisco, CA",
    type: "Commercial",
  },
  {
    id: 9,
    images: [apartment1, apartment2, apartment3, apartment1],
    price: "250 000",
    room: 3,
    area: 150,
    currFloor: "10",
    building: "15",
    location: "New York City, NY",
    type: "Apartment",
  },
  {
    id: 10,
    images: [apartment1, apartment2, apartment3, apartment1],
    price: "300 000",
    room: 4,
    area: 180,
    currFloor: "10",
    building: "15",
    location: "Los Angeles, CA",
    type: "House",
  },
  {
    id: 11,
    images: [apartment1, apartment2, apartment3, apartment1],
    price: "400 000",
    room: 5,
    area: 200,
    currFloor: "10",
    building: "15",
    location: "Miami, FL",
    type: "Villa",
  },
  {
    id: 12,
    images: [apartment1, apartment2, apartment3, apartment1],
    price: "500 000",
    room: 6,
    area: 250,
    currFloor: "10",
    building: "15",
    location: "San Francisco, CA",
    type: "Commercial",
  },
];
